 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'AED',	'United Arab Emirates Dirham'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'AFN',	'Afghan Afghani'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ALL',	'Albanian Lek'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'AMD',	'Armenian Dram'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ANG',	'Netherlands Antillean Guilder'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'AOA',	'Angolan Kwanza'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ARS',	'Argentine Peso'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'AUD',	'Australian Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'AWG',	'Aruban Florin'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'AZN',	'Azerbaijani Manat'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BAM',	'Bosnia-Herzegovina Convertible Mark'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BBD',	'Barbadian Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BDT',	'Bangladeshi Taka'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BGN',	'Bulgarian Lev'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BHD',	'Bahraini Dinar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BIF',	'Burundian Franc'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BMD',	'Bermudan Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BND',	'Brunei Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BOB',	'Bolivian Boliviano'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BRL',	'Brazilian Real'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BSD',	'Bahamian Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BTC',	'Bitcoin'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BTN',	'Bhutanese Ngultrum'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BWP',	'Botswanan Pula'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BYR',	'Belarusian Ruble'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'BZD',	'Belize Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CAD',	'Canadian Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CDF',	'Congolese Franc'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CHF',	'Swiss Franc'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CLF',	'Chilean Unit of Account (UF)'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CLP',	'Chilean Peso'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CNY',	'Chinese Yuan'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'COP',	'Colombian Peso'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CRC',	'Costa Rican Colón'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CUC',	'Cuban Convertible Peso'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CUP',	'Cuban Peso'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CVE',	'Cape Verdean Escudo'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'CZK',	'Czech Republic Koruna'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'DJF',	'Djiboutian Franc'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'DKK',	'Danish Krone'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'DOP',	'Dominican Peso'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'DZD',	'Algerian Dinar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'EEK',	'Estonian Kroon'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'EGP',	'Egyptian Pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ERN',	'Eritrean Nakfa'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ETB',	'Ethiopian Birr'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'EUR',	'Euro'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'FJD',	'Fijian Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'FKP',	'Falkland Islands Pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'GBP',	'British Pound Sterling'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'GEL',	'Georgian Lari'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'GGP',	'Guernsey Pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'GHS',	'Ghanaian Cedi'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'GIP',	'Gibraltar Pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'GMD',	'Gambian Dalasi'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'GNF',	'Guinean Franc'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'GTQ',	'Guatemalan Quetzal'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'GYD',	'Guyanaese Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'HKD',	'Hong Kong Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'HNL',	'Honduran Lempira'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'HRK',	'Croatian Kuna'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'HTG',	'Haitian Gourde'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'HUF',	'Hungarian Forint'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'IDR',	'Indonesian Rupiah'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ILS',	'Israeli New Sheqel'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'IMP',	'Manx pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'INR',	'Indian Rupee'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'IQD',	'Iraqi Dinar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'IRR',	'Iranian Rial'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ISK',	'Icelandic Króna'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'JEP',	'Jersey Pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'JMD',	'Jamaican Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'JOD',	'Jordanian Dinar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'JPY',	'Japanese Yen'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'KES',	'Kenyan Shilling'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'KGS',	'Kyrgystani Som'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'KHR',	'Cambodian Riel'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'KMF',	'Comorian Franc'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'KPW',	'North Korean Won'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'KRW',	'South Korean Won'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'KWD',	'Kuwaiti Dinar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'KYD',	'Cayman Islands Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'KZT',	'Kazakhstani Tenge'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'LAK',	'Laotian Kip'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'LBP',	'Lebanese Pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'LKR',	'Sri Lankan Rupee'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'LRD',	'Liberian Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'LSL',	'Lesotho Loti'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'LTL',	'Lithuanian Litas'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'LVL',	'Latvian Lats'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'LYD',	'Libyan Dinar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MAD',	'Moroccan Dirham'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MDL',	'Moldovan Leu'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MGA',	'Malagasy Ariary'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MKD',	'Macedonian Denar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MMK',	'Myanma Kyat'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MNT',	'Mongolian Tugrik'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MOP',	'Macanese Pataca'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MRO',	'Mauritanian Ouguiya'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MTL',	'Maltese Lira'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MUR',	'Mauritian Rupee'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MVR',	'Maldivian Rufiyaa'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MWK',	'Malawian Kwacha'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MXN',	'Mexican Peso'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MYR',	'Malaysian Ringgit'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'MZN',	'Mozambican Metical'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'NAD',	'Namibian Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'NGN',	'Nigerian Naira'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'NIO',	'Nicaraguan Córdoba'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'NOK',	'Norwegian Krone'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'NPR',	'Nepalese Rupee'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'NZD',	'New Zealand Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'OMR',	'Omani Rial'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'PAB',	'Panamanian Balboa'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'PEN',	'Peruvian Nuevo Sol'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'PGK',	'Papua New Guinean Kina'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'PHP',	'Philippine Peso'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'PKR',	'Pakistani Rupee'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'PLN',	'Polish Zloty'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'PYG',	'Paraguayan Guarani'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'QAR',	'Qatari Rial'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'RON',	'Romanian Leu'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'RSD',	'Serbian Dinar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'RUB',	'Russian Ruble'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'RWF',	'Rwandan Franc'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SAR',	'Saudi Riyal'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SBD',	'Solomon Islands Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SCR',	'Seychellois Rupee'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SDG',	'Sudanese Pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SEK',	'Swedish Krona'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SGD',	'Singapore Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SHP',	'Saint Helena Pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SLL',	'Sierra Leonean Leone'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SOS',	'Somali Shilling'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SRD',	'Surinamese Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'STD',	'São Tomé and Príncipe Dobra'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SVC',	'Salvadoran Colón'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SYP',	'Syrian Pound'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'SZL',	'Swazi Lilangeni'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'THB',	'Thai Baht'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'TJS',	'Tajikistani Somoni'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'TMT',	'Turkmenistani Manat'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'TND',	'Tunisian Dinar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'TOP',	'Tongan Paʻanga'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'TRY',	'Turkish Lira'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'TTD',	'Trinidad and Tobago Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'TWD',	'New Taiwan Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'TZS',	'Tanzanian Shilling'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'UAH',	'Ukrainian Hryvnia'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'UGX',	'Ugandan Shilling'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'USD',	'United States Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'UYU',	'Uruguayan Peso'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'UZS',	'Uzbekistan Som'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'VEF',	'Venezuelan Bolívar Fuerte'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'VND',	'Vietnamese Dong'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'VUV',	'Vanuatu Vatu'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'WST',	'Samoan Tala'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'XAF',	'CFA Franc BEAC'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'XAG',	'Silver (troy ounce)'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'XAU',	'Gold (troy ounce)'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'XCD',	'East Caribbean Dollar'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'XDR',	'Special Drawing Rights'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'XOF',	'CFA Franc BCEAO'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'XPD',	'Palladium Ounce'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'XPF',	'CFP Franc'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'XPT',	'Platinum Ounce'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'YER',	'Yemeni Rial'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ZAR',	'South African Rand'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ZMK',	'Zambian Kwacha (pre-2013)'	);
 INSERT INTO `Currency` (  `shortname` , `name` )  values(	'ZMW' 	'Zambian Kwacha' 	);
	 	 	
